package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/pkg/errors"
	rootconfig "github.com/vcnkl/rpm/config"
	"github.com/vcnkl/rpm/environments/spec"
)

const RepoRootToken = "${REPO_ROOT}"

func Render(env *spec.ResolvedEnvironment) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by rpm. Do not edit.\n\n")
	writeCall(&buf, "rpm_environment", []field{
		{name: "name", value: quote(env.Name)},
		{name: "live_reload", value: dict(map[string]string{
			"debounce": quote(env.ReloadPolicy.Debounce),
			"enabled":  boolValue(env.ReloadPolicy.Enabled),
		})},
		{name: "variables", value: envDict(env.Variables)},
	})
	buf.WriteByte('\n')

	dependencies := append([]spec.Dependency{}, env.Dependencies...)
	sort.Slice(dependencies, func(i, j int) bool {
		return dependencies[i].Ref < dependencies[j].Ref
	})
	for _, dep := range dependencies {
		writeCall(&buf, "rpm_dependency", []field{
			{name: "ref", value: quote(dep.Ref)},
			{name: "config", value: quote(dep.ConfigPath)},
		})
	}
	if len(dependencies) > 0 {
		buf.WriteByte('\n')
	}

	for _, before := range env.BeforeTargets {
		writeCall(&buf, "rpm_before_target", []field{
			{name: "ref", value: quote(before.Ref)},
			{name: "config", value: quote(before.ConfigPath)},
		})
	}
	if len(env.BeforeTargets) > 0 {
		buf.WriteByte('\n')
	}

	for _, dep := range env.DepTargets {
		writeCall(&buf, "rpm_dep_target", []field{
			{name: "ref", value: quote(dep.Ref)},
			{name: "config", value: quote(dep.ConfigPath)},
		})
	}
	if len(env.DepTargets) > 0 {
		buf.WriteByte('\n')
	}

	targets := append([]spec.Target{}, env.Targets...)
	sort.Slice(targets, func(i, j int) bool {
		return targets[i].Ref < targets[j].Ref
	})
	for _, target := range targets {
		writeCall(&buf, "rpm_target", []field{
			{name: "ref", value: quote(target.Ref)},
			{name: "config", value: quote(target.ConfigPath)},
			{name: "env", value: envDict(target.OverrideEnv)},
			{name: "reload", value: boolValue(target.Reload)},
		})
	}
	if len(targets) > 0 {
		buf.WriteByte('\n')
	}

	order := make([]string, 0, len(env.BeforeTargets)+len(dependencies)+len(env.DepTargets)+len(targets))
	for _, before := range env.BeforeTargets {
		order = append(order, before.Ref)
	}
	for _, dep := range dependencies {
		order = append(order, dep.Ref)
	}
	for _, dep := range env.DepTargets {
		order = append(order, dep.Ref)
	}
	for _, target := range targets {
		order = append(order, target.Ref)
	}
	writeCall(&buf, "rpm_run", []field{{name: "order", value: orderedStringList(order)}})

	return buf.Bytes(), nil
}

func Write(repo *rootconfig.Config, env *spec.ResolvedEnvironment, out string) (string, error) {
	if out == "" {
		out = CachePath(repo, env.Name)
	}
	data, err := Render(env)
	if err != nil {
		return "", err
	}
	data = portableData(repo, data)
	if err := os.MkdirAll(filepath.Dir(out), 0755); err != nil {
		return "", errors.Wrap(err, "failed to create Starlark output directory")
	}
	if err := os.WriteFile(out, data, 0644); err != nil {
		return "", errors.Wrap(err, "failed to write generated Starlark")
	}
	return out, nil
}

func CachePath(repo *rootconfig.Config, blueprint string) string {
	return filepath.Join(repo.RepoRoot(), ".rpm", "envs", blueprint, "runtime.gen.star")
}

func portableData(repo *rootconfig.Config, data []byte) []byte {
	root := filepath.ToSlash(repo.RepoRoot())
	if root == "" {
		return data
	}
	return []byte(strings.ReplaceAll(string(data), root, RepoRootToken))
}

type field struct {
	name  string
	value string
}

func writeCall(buf *bytes.Buffer, name string, fields []field) {
	buf.WriteString(name)
	buf.WriteString("(\n")
	for _, field := range fields {
		fmt.Fprintf(buf, "    %s = %s,\n", field.name, field.value)
	}
	buf.WriteString(")\n")
}

func envDict(values []spec.EnvVar) string {
	fields := make(map[string]string, len(values))
	for _, value := range values {
		fields[value.Name] = quote(value.Value)
	}
	return dict(fields)
}

func dict(values map[string]string) string {
	if len(values) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var buf bytes.Buffer
	buf.WriteString("{")
	for i, key := range keys {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(quote(key))
		buf.WriteString(": ")
		buf.WriteString(values[key])
	}
	buf.WriteString("}")
	return buf.String()
}

func stringList(values []string) string {
	items := append([]string{}, values...)
	sort.Strings(items)
	return orderedStringList(items)
}

func orderedStringList(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	var buf bytes.Buffer
	buf.WriteString("[")
	for i, value := range values {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(quote(value))
	}
	buf.WriteString("]")
	return buf.String()
}

func boolValue(value bool) string {
	if value {
		return "True"
	}
	return "False"
}

func quote(value string) string {
	return strconv.Quote(value)
}
