package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"

	"github.com/pkg/errors"
	rootconfig "github.com/vcnkl/rpm/config"
	"github.com/vcnkl/rpm/environments/spec"
)

func Render(env *spec.ResolvedEnvironment) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Generated by rpm. Do not edit.\n\n")
	writeCall(&buf, "rpm_environment", []field{
		{name: "name", value: quote(env.Name)},
		{name: "live_reload", value: dict(map[string]string{
			"debounce": quote(env.ReloadPolicy.Debounce),
			"enabled":  boolValue(env.ReloadPolicy.Enabled),
		})},
		{name: "variables", value: envDict(env.Variables)},
	})
	buf.WriteByte('\n')

	dependencies := append([]spec.Dependency{}, env.Dependencies...)
	sort.Slice(dependencies, func(i, j int) bool {
		return dependencies[i].Ref < dependencies[j].Ref
	})
	for _, dep := range dependencies {
		writeCall(&buf, "rpm_dependency", []field{
			{name: "ref", value: quote(dep.Ref)},
			{name: "name", value: quote(dep.Name)},
			{name: "image", value: quote(dep.Image)},
			{name: "mode", value: quote(string(dep.Mode))},
			{name: "env", value: envDict(dep.Env)},
			{name: "ports", value: stringList(dep.Ports)},
			{name: "volumes", value: stringList(dep.Volumes)},
		})
	}
	if len(dependencies) > 0 {
		buf.WriteByte('\n')
	}

	for _, before := range env.BeforeTargets {
		writeCall(&buf, "rpm_before_target", []field{
			{name: "ref", value: quote(before.Ref)},
			{name: "command", value: quote(before.Command)},
			{name: "workdir", value: quote(before.WorkingDir)},
			{name: "env", value: envDict(before.Env)},
		})
	}
	if len(env.BeforeTargets) > 0 {
		buf.WriteByte('\n')
	}

	targets := append([]spec.Target{}, env.Targets...)
	sort.Slice(targets, func(i, j int) bool {
		return targets[i].Ref < targets[j].Ref
	})
	for _, target := range targets {
		writeCall(&buf, "rpm_target", []field{
			{name: "ref", value: quote(target.Ref)},
			{name: "command", value: quote(target.Command)},
			{name: "workdir", value: quote(target.WorkingDir)},
			{name: "env", value: envDict(target.ExplicitEnv)},
			{name: "reload", value: boolValue(target.Reload)},
		})
		writeCall(&buf, "rpm_watch", []field{
			{name: "target", value: quote(target.Ref)},
			{name: "roots", value: stringList(target.Watch.Roots)},
			{name: "ignore", value: stringList(target.Watch.Ignore)},
			{name: "reload", value: boolValue(target.Watch.Reload)},
			{name: "enabled", value: boolValue(target.Watch.Enabled)},
		})
	}
	if len(targets) > 0 {
		buf.WriteByte('\n')
	}

	order := make([]string, 0, len(env.RuntimeUnits))
	units := append([]spec.RuntimeUnit{}, env.RuntimeUnits...)
	sort.Slice(units, func(i, j int) bool {
		if units[i].Kind == units[j].Kind {
			return units[i].Id < units[j].Id
		}
		return units[i].Kind < units[j].Kind
	})
	for _, unit := range units {
		order = append(order, unit.Id)
	}
	writeCall(&buf, "rpm_run", []field{{name: "order", value: orderedStringList(order)}})

	return buf.Bytes(), nil
}

func Write(repo *rootconfig.Config, env *spec.ResolvedEnvironment, out string) (string, error) {
	if out == "" {
		out = CachePath(repo, env.Name)
	}
	data, err := Render(env)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(out), 0755); err != nil {
		return "", errors.Wrap(err, "failed to create Starlark output directory")
	}
	if err := os.WriteFile(out, data, 0644); err != nil {
		return "", errors.Wrap(err, "failed to write generated Starlark")
	}
	return out, nil
}

func CachePath(repo *rootconfig.Config, blueprint string) string {
	return filepath.Join(repo.RepoRoot(), ".rpm", "cache", "starlark", blueprint, "env.star")
}

type field struct {
	name  string
	value string
}

func writeCall(buf *bytes.Buffer, name string, fields []field) {
	buf.WriteString(name)
	buf.WriteString("(\n")
	for _, field := range fields {
		fmt.Fprintf(buf, "    %s = %s,\n", field.name, field.value)
	}
	buf.WriteString(")\n")
}

func envDict(values []spec.EnvVar) string {
	fields := make(map[string]string, len(values))
	for _, value := range values {
		fields[value.Name] = quote(value.Value)
	}
	return dict(fields)
}

func dict(values map[string]string) string {
	if len(values) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var buf bytes.Buffer
	buf.WriteString("{")
	for i, key := range keys {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(quote(key))
		buf.WriteString(": ")
		buf.WriteString(values[key])
	}
	buf.WriteString("}")
	return buf.String()
}

func stringList(values []string) string {
	items := append([]string{}, values...)
	sort.Strings(items)
	return orderedStringList(items)
}

func orderedStringList(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	var buf bytes.Buffer
	buf.WriteString("[")
	for i, value := range values {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(quote(value))
	}
	buf.WriteString("]")
	return buf.String()
}

func boolValue(value bool) string {
	if value {
		return "True"
	}
	return "False"
}

func quote(value string) string {
	return strconv.Quote(value)
}
