# Generated by rpm. Do not edit.

rpm_environment(
    name = "local-stack",
    live_reload = {"debounce": "100ms", "enabled": True},
    variables = {"LOG_LEVEL": "debug"},
)

rpm_dependency(
    ref = "go-app:postgres",
    name = "postgres",
    image = "postgres:16",
    mode = "shared",
    env = {"POSTGRES_PASSWORD": "example"},
    ports = ["5432:5432"],
    volumes = ["postgres-data:/var/lib/postgresql/data"],
)
rpm_dependency(
    ref = "python-app:redis",
    name = "redis",
    image = "redis:7",
    mode = "dedicated",
    env = {},
    ports = ["6379:6379"],
    volumes = [],
)
rpm_dependency(
    ref = "ts-app:mailhog",
    name = "mailhog",
    image = "mailhog/mailhog:v1.0.1",
    mode = "shared",
    env = {},
    ports = ["1025:1025", "8025:8025"],
    volumes = [],
)

rpm_target(
    ref = "go-app:serve",
    command = "echo \"REPO_ROOT=$REPO_ROOT BUNDLE_ROOT=$BUNDLE_ROOT GO_VAR=$GO_VAR APP_PORT=$APP_PORT BUILD_MODE=$BUILD_MODE GLOBAL_VAR=$GLOBAL_VAR\"",
    workdir = "<repo>/apps/go-app",
    env = {"APP_PORT": "8080", "BUNDLE_ROOT": "<repo>/apps/go-app", "DB_HOST": "localhost", "DB_PORT": "5432", "GLOBAL_VAR": "global_value", "GO_VAR": "go_value", "LOCAL_SECRET": "secret_from_dotenv", "LOG_LEVEL": "debug", "PROJECT_NAME": "sample-repo", "REPO_ROOT": "<repo>"},
    reload = True,
)
rpm_watch(
    target = "go-app:serve",
    roots = ["<repo>/apps/go-app"],
    ignore = ["bin/**"],
    reload = True,
    enabled = True,
)
rpm_target(
    ref = "python-app:serve",
    command = "echo \"REPO_ROOT=$REPO_ROOT BUNDLE_ROOT=$BUNDLE_ROOT PYTHON_VAR=$PYTHON_VAR\"",
    workdir = "<repo>/apps/python-app",
    env = {"BUNDLE_ROOT": "<repo>/apps/python-app", "GLOBAL_VAR": "global_value", "LOG_LEVEL": "debug", "PROJECT_NAME": "sample-repo", "PYTHON_VAR": "python_value", "REPO_ROOT": "<repo>"},
    reload = False,
)
rpm_watch(
    target = "python-app:serve",
    roots = ["<repo>/apps/python-app"],
    ignore = [],
    reload = False,
    enabled = False,
)
rpm_target(
    ref = "ts-app:web",
    command = "echo \"REPO_ROOT=$REPO_ROOT BUNDLE_ROOT=$BUNDLE_ROOT TS_VAR=$TS_VAR\"",
    workdir = "<repo>/apps/ts-app",
    env = {"BUNDLE_ROOT": "<repo>/apps/ts-app", "GLOBAL_VAR": "global_value", "LOG_LEVEL": "debug", "PROJECT_NAME": "sample-repo", "REPO_ROOT": "<repo>", "TS_VAR": "typescript_value"},
    reload = True,
)
rpm_watch(
    target = "ts-app:web",
    roots = ["<repo>/apps/ts-app"],
    ignore = [],
    reload = True,
    enabled = True,
)

rpm_run(
    order = ["go-app:postgres", "python-app:redis", "ts-app:mailhog", "go-app:serve", "python-app:serve", "ts-app:web"],
)
