# Generated by rpm. Do not edit.

rpm_environment(
    name = "local-stack",
    live_reload = {"debounce": "100ms", "enabled": True},
    variables = {"LOG_LEVEL": "debug"},
)

rpm_dependency(
    ref = "mailhog",
    config = "repo.yml",
)
rpm_dependency(
    ref = "postgres",
    config = "repo.yml",
)
rpm_dependency(
    ref = "redis",
    config = "repo.yml",
)

rpm_before_target(
    ref = "go-app:before_file",
    config = "apps/go-app/rpm.yml",
)
rpm_before_target(
    ref = "go-app:before_inline",
    config = "apps/go-app/rpm.yml",
)
rpm_before_target(
    ref = "go-app:prepare",
    config = "apps/go-app/rpm.yml",
)

rpm_target(
    ref = "go-app:echo-123",
    config = "apps/go-app/rpm.yml",
    env = {"APP_PORT": "8080"},
    reload = True,
)
rpm_target(
    ref = "python-app:echo-456",
    config = "apps/python-app/rpm.yml",
    env = {},
    reload = False,
)
rpm_target(
    ref = "ts-app:web",
    config = "apps/ts-app/rpm.yml",
    env = {},
    reload = True,
)

rpm_run(
    order = ["go-app:before_file", "go-app:before_inline", "go-app:prepare", "mailhog", "postgres", "redis", "go-app:echo-123", "python-app:echo-456", "ts-app:web"],
)
